# For more info on HTTP files go to https://aka.ms/vs/httpfile
POST http://localhost:5293/users
Content-Type: application/json

{
  "username": "mprattinger",
  "email": "mprattinger@outlook.com",
  "password": "Fl61291420"  
}