# For more info on HTTP files go to https://aka.ms/vs/httpfile
POST https://localhost:7281/users
Content-Type: application/json

{
  "username": "mprattinger",
  "email": "mprattinger@outlook.com",
  "password": "Fl61291420"  
}