// <auto-generated />
using System;
using FSTime.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
#pragma warning disable CS8981 // The type name only contains lower-cased ascii characters. Such names may become reserved for the language.
#nullable disable

namespace FSTime.Infrastructure.Migrations
{
    [DbContext(typeof(FSTimeDbContext))]
    [Migration("20250220225156_trupdate")]
    partial class trupdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FSTime.Domain.TenantAggregate.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsLicensed")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("FSTime.Domain.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FSTime.Domain.TenantAggregate.Tenant", b =>
                {
                    b.OwnsMany("FSTime.Domain.Common.ValueObjects.TenantRole", "_users", b1 =>
                        {
                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("RoleName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("TenantId", "UserId");

                            b1.HasIndex("UserId")
                                .IsUnique();

                            b1.ToTable("TenantRoles", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TenantId");

                            b1.HasOne("FSTime.Domain.UserAggregate.User", null)
                                .WithOne()
                                .HasForeignKey("FSTime.Domain.TenantAggregate.Tenant._users#FSTime.Domain.Common.ValueObjects.TenantRole", "UserId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();
                        });

                    b.Navigation("_users");
                });
#pragma warning restore 612, 618
        }
    }
}
