@ACCESS_JWT=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTk1OWM1Mi0wZjIyLTc2MGEtOTBkYS03OTVhMTI2NGJjNzciLCJqdGkiOiJjZDJlYzk4Ny1hNGVmLTQxZDAtOGExMC02N2I4YjJjMGRkZTciLCJuYW1lIjoibXByYXR0aW5nZXIiLCJVTVVJRCI6IjAxOTU5YzUyLTBmMjItNzYwYS05MGRhLTc5NWExMjY0YmM3NyIsImV4cCI6MTc0MjE1NDI3OSwiaXNzIjoiRlNUaW1lIiwiYXVkIjoiRlNUaW1lIn0.qFaJt78rtcKdGRm_2emEDA7ZZvKT06QzruyU9d6QkTI


POST https://localhost:7281/tenants
Content-Type: application/json
Authorization: Bearer {{ACCESS_JWT}}

{
  "name": "FlintSoft"
}

###
GET http://localhost:5293/tenants
Content-Type: application/json
Authorization: Bearer {{ACCESS_JWT}}