@ACCESS_JWT=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlYjJhNmZhYi0xMmVhLTRiMjItOTcyZC03ZTY0MmVkODJmODgiLCJqdGkiOiIwMDQwZGQ1Ni1lODQ0LTQwOGQtYjQ3OS02MDcxNGMyZTUyZTMiLCJuYW1lIjoibXByYXR0aW5nZXIiLCJVTVVJRCI6ImViMmE2ZmFiLTEyZWEtNGIyMi05NzJkLTdlNjQyZWQ4MmY4OCIsImV4cCI6MTc0MDA5NTA3MiwiaXNzIjoiRlNUaW1lIiwiYXVkIjoiRlNUaW1lIn0.NfjI__2llLmJlwalv7dIW6nM3Vgcu93twlG_RTK2w-g


POST http://localhost:5293/tenants
Content-Type: application/json
Authorization: Bearer {{ACCESS_JWT}}

{
  "name": "FlintSoft"
}

###
GET http://localhost:5293/tenants
Content-Type: application/json
Authorization: Bearer {{ACCESS_JWT}}