@ACCESS_JWT=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlYjJhNmZhYi0xMmVhLTRiMjItOTcyZC03ZTY0MmVkODJmODgiLCJqdGkiOiI1YjUxNTIwOS03NzE0LTRiMjAtODU0ZS1hMGFjYzlmOTQ3NGYiLCJuYW1lIjoibXByYXR0aW5nZXIiLCJVTVVJRCI6ImViMmE2ZmFiLTEyZWEtNGIyMi05NzJkLTdlNjQyZWQ4MmY4OCIsImV4cCI6MTc0MDA4OTk3OSwiaXNzIjoiRlNUaW1lIiwiYXVkIjoiRlNUaW1lIn0.jcwnIs_9mJFXow_8Da9Yb6RJLcL33X6wC0mBPDOP2HA


POST http://localhost:5293/tenants
Content-Type: application/json
Authorization: Bearer {{ACCESS_JWT}}

{
  "name": "FlintSoft"
}